### ISSUE TITLE
Out of bounds read in mersenne-twister.cpp

### ISSUE THREAD

**Issue by nyalldawson** [cslarsen/mersenne-twister#1]
I've recently run a Coverity scan over a project which includes this library. It's flagged mersenne-twister.cpp line 76 as an out of bounds read for MT. I've double checked and it looks like an error to me, as in the for loop in line 66 i ranges from [0, 226]. Line 74 increments i by one, so the max value of i will be 227. Then, in line 76, MT[ 227 + 397 ](MT[624]) is read, which is outside the bounds of MT.

**Comment by cslarsen** [comment]
Thanks a bunch! You're probably right. I'll have a look.

**Comment by cslarsen** [comment]
I double checked that you are right. I've added a very quick fix for it, but will look more into this.

**Comment by cslarsen** [comment]
Fixed in 11446a63f4e8a580fea8e1443301eb5a08bd1b85

Thanks for reporting this! I've added your name to AUTHORS and README. If you don't want it listed, let me know.

**Comment by nyalldawson** [comment]
@cslarsen Great - this fix is much appreciated!
